version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./data:/var/www/html/data
      - ./attached_assets:/var/www/html/attached_assets
    restart: unless-stopped